<?php

/**
 * Class to use PHPDocX with a namespace
 *
 * @category   Phpdocx
 * @package    factory
 * @copyright  Copyright (c) Narcea Producciones Multimedia S.L.
 *             (http://www.2mdc.com)
 * @license    http://www.phpdocx.com/wp-content/themes/lightword/pro_license.php
 * @version    2013.06.20
 * @link       http://www.phpdocx.com
 * @since      2013.06.20
 */

require_once dirname(__FILE__) . '/CreateDocx.inc';

class Phpdocx_Phpdocx extends CreateDocx {
}
